#numpy 練習

##import numpy

In [ ]:
import numpy as np

In [ ]:
x = np.array(
             [0, 1, 2, 3, 4]
            )

In [ ]:
idx = [1, 3]
x[idx]

array([1, 3])

In [ ]:
x[idx] = 7

In [ ]:
x


array([0, 7, 2, 7, 4])

In [ ]:
x[idx] = (8, 9 )

In [ ]:
x

array([0, 8, 2, 9, 4])

In [ ]:
y = x[idx]

In [ ]:
y

array([8, 9])

In [ ]:
y[[1, 0, 1]]

array([9, 8, 9])

In [ ]:
x = np.array([0, 1, 2])

In [ ]:
idx = np.array([True, False, True])

In [ ]:
x[idx]

array([0, 2])

In [ ]:
x[idx] = 7

In [ ]:
x

array([0, 1, 2])

In [ ]:
! np.max()

/bin/bash: -c: line 1: syntax error: unexpected end of file


In [ ]:
? np.max

In [ ]:
import numpy as np

In [ ]:
a  = np.array([[1, 2],[3, 4]])

In [ ]:
a.shape

(2, 2)

In [ ]:
a.max(1) #取a陣列裡的1的位置的數值

array([2, 4])

In [ ]:
a.max(0)

array([3, 4])

In [ ]:
np.max(a) #取a 陣列裡的最大值

4

In [ ]:
np.max(a, axis = 0)

array([3, 4])

In [ ]:
np.max(a, axis = 1) #取第1軸內最大的值

array([2, 4])

In [ ]:
y  = np.max(a, axis = 0)

In [ ]:
y

array([3, 4])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.shape #檢視numpy

(2, 2, 2)

In [ ]:
a.ndim #檢視nump是幾軸陣列

3

##陣列重塑(reshape):改變陣列形狀



In [ ]:
a = np.arange(1, 9).reshape(2, 2, 2) #創造一個1到8陣列,將陣列轉換成2x2x2的陣列

In [ ]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
x = np.array(
              [
               [
                [1, 2], [3, 4]
               ],
               [
                [5, 6], [7, 8]
               ]
              ]
            )

In [ ]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
y = np.reshape(x, (2, 4))

In [ ]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
z = np.array([[1, 2], [3, 4]]) + np.array([[1, 2], [3, 4]])

In [ ]:
z

array([[2, 4],
       [6, 8]])

In [ ]:
z.shape

(2, 2)

In [ ]:

g = np.array([[1, 2]]) * np.array([3, 4])

In [ ]:
g


array([[3, 8]])

In [ ]:
np.array([1, 3]) > np.array([2, 2]) #比較陣列裡的數值

array([False,  True])

##陣列擴張

In [3]:
import numpy as np
np.array([[1, 2], [3, 4]]) + np.array([1, 2]) #shape(2,2) + shape(2)

array([[2, 4],
       [4, 6]])

In [5]:
 r = np.array([[1], [2]]) + np.array([3, 4])
 r

array([[4, 5],
       [5, 6]])

In [ ]:
r.shape

(2, 2)

In [ ]:
a = np.array(
              [
               [
                [1],
                [2]
               ]   
              ]
             )

In [ ]:
a.shape

(1, 2, 1)

In [ ]:
a = np.array(
              [
               [
                [1, 2],
                [3, 4]
               ],
               [
                [5, 6],
                [7, 8]
               ]
              ]
            )

In [ ]:
a.shape

(2, 2, 2)

In [ ]:
np.max(a, axis = 0)

array([[5, 6],
       [7, 8]])

In [ ]:
np.max(a, axis = 1)

array([[3, 4],
       [7, 8]])

In [ ]:
np.max(a, axis = 2)

array([[2, 4],
       [6, 8]])